name: Changelog Verifier

on:
  pull_request:
    types: [opened, edited, review_requested, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v5

      # Automatically update changelog on Dependabot pull requests
      - uses: dangoslen/dependabot-changelog-helper@v4.2.1
        with:
          activationLabels: dependencies # run on any pull request labeled with dependencies (which is added by Dependabot as a default)
          dependencyTool: dependabot

      # This step is required for committing the changes to your branch.
      # See https://github.com/stefanzweifel/git-auto-commit-action#commits-of-this-action-do-not-trigger-new-workflow-runs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(deps): updated changelog"

      # Enforces the update of a changelog file on every pull request
      - uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: "autocut, skip-changelog"
